language: generic
branches:
  only:
    - master

sudo: required

before_install:
  - wget https://releases.hashicorp.com/consul-template/0.18.1/consul-template_0.18.1_linux_amd64.zip -O ctmpl.zip
  - unzip -o ctmpl.zip
  - chmod a+x consul-template
  - consul-template -consul-addr=52.14.96.95:8500 -template=test.ctmpl -dry -once

script:
  - ls
